### ISSUE TITLE
Comments on CoCreation0_IntroToPython

### ISSUE THREAD

**Issue by meevans1** [ynyrharris/notebooks-collection-opendata#1]
Will you make a commit where all the cell output has been removed so that they don't already have the "answers"?

I would ask yourself "which bits of python do they need for the following notebooks?" Do they need to know `break`, for example? If not I would take it out to be brief and get onto more interesting stuff :)

I would encourage you to opt for simplicity of presentation over everything :) Some suggestions below.

I think "As an interpreted language, no manual compilation (translation from human-readable code to machine-usable code) is necessary, which facilitates rapid development and swift experimentation." is not important for beginners.
I think you should change "edit rich text" -> "edit text". "rich" won't be clear to beginners.
I think you should remove the word "markup". The fewer new terms you introduce the better :)
I think it's best to avoid things like "It is easy" when teaching. What if they don't find it easy.
I think the "(highlighting the encompassing cell)" can be removed as it's a bit confusing and the instructions work without.
I think "syntax" could be a new word for them, so maybe "basic principles"?
I think you can remove "Because Python is such a simple language, this programme is in fact not especially interesting.". Again, comment about "simple" (what if they don't find it simple) and this sentence doesn't really add any info.
I think you can remove the sentence "In Python, numbers are numbers and are treated by the interpreter as you would expect. " The "numbers are numbers" is a bit confusing, "interpreter" will probably be new to them and what if they don't know what to expect!
I think change "Evaluate" to "Run" because you've already used the word "run".
I think you can remove the cells for "floor-division, modulo". These may be new words to them and they probably aren't used in the following notebooks.
I think you can remove "Python is special in that in x = 4, the type of x does not have to be declared." If python is their first language then this won't be important.
I think the sentence "The type of the variable is the type of the value." reads a bit confusing. I personally think it can be removed.
I would try phrase simpler than "amenable". Maybe "Strings can undergo the above"?
I think some explanatory text is needed above each of the cells word[0], word[-1], word[1:5]. Like "here we access the 1st character in the string, starting from 0!"
I think you can remove "(a sequence type)".
You should definitely put "llanfairpg" instead of "super...." ;)
I think you can remove "by the interpreter". I don't think they need to know this detail.
I think you can remove "straightforward". Same comment as "easy".
I think you can remove " (as in most other languages)". They only need python here :)
I think you can remove "innermost"

**Comment by ynyrharris** [comment]
Diolch Meirin, here is a list of the changes I made based on these issues

*Introduction*
- Removed output from commits
- Removed the section on `break`, `continue` and `pass`
- Removed "As an interpreted language..." sentence
- "edit rich text" -> "write and edit text boxes"
- "markup" -> ""
- Removed comments about easiness globally
- " (highlighting the encompassing cell)," -> ","

*Hello, World*
- "syntax" -> "basics"
- Remove comment "Because Python is a simple language..."

*Numbers, Strings, and Compound Data Types*
- Remove confusing introduction to maths in Python, replacing with "Python is good at maths!"
- "Evaluate" -> "Run" since run has already been used with this meaning
- Removed the floor-division and modulo operators
- Removed allusion that Python is not declarative
- "are amenable" -> "may be operated upon" - admittedly a more complicated sentence, but one made of simpler words
- Commented the code cells that access the characters of a string by index
- " (a sequence type)" -> ""
- "Llanfairpg..." instead of "supercal..." will get its own commit

*Control Flow*
- Removed "by the interpreter"
- Removed "straightforward" claim
- Removed mention of other languages

**Comment by meevans1** [comment]
All sound like good changes to me!
